### ISSUE TITLE
The difference between CMSIS_V1 and CMSIS_V2 

### ISSUE THREAD

**Issue by ericellis7** [STMicroelectronics/cmsis-core#1]
## IMPORTANT INFORMATION 

Hi ，
    I use STM32CubeMX v5.6 ，FB Package v1.16，middleware FreeRTOS，interface have V1 and V2 ，
how do I choose ? 
    thanks

**Comment by RKOUSTM** [comment]
Hi @EricMzky,

Thank you for this report. 

In fact, CMSIS-RTOS (v1 or v2)  is a standardized RTOS abstraction from ARM. It provides a standardized API for software components that require RTOS functionality and gives therefore serious benefits to the users and the software industry. This [link](https://www.keil.com/pack/doc/CMSIS/RTOS2/html/os2MigrationFunctions.html) describes the CMSIS-RTOS API v1 and API v2 functions with the differences in functionality.  

The [CMSIS-RTOS v1](https://www.keil.com/pack/doc/CMSIS/RTOS/html/index.html) is designed for Cortex-M processor-based devices. It allows software components to run on multiple RTOS systems. On the other hand, the [CMSIS-RTOS v2](https://www.keil.com/pack/doc/CMSIS/RTOS2/html/index.html) is an extension of CMSIS-RTOS v1 with support of Armv8-M, creation of dynamic objects, provisions for multi-core systems, binary compatible interface. In your case you can use CMSIS RTOS version 2 for your application development with FreeRTOS. 

For further information about the development of an application using STM32Cube with RTOS, you can refer to this [UM1722](https://www.st.com/resource/en/user_manual/dm00105262-developing-applications-on-stm32cube-with-rtos-stmicroelectronics.pdf).

I hope the links I provided were helpful. Thank you again for your report. 

Please allow me to close this issue now. We are looking forward to reading from you again.

with regards,
