### ISSUE TITLE
SHA256 change for CMSIS core v5.4.0_cm4

### ISSUE THREAD

**Issue by tpudlik** [STMicroelectronics/cmsis-core#6]
The SHA256 of the archive https://github.com/STMicroelectronics/cmsis_core/archive/refs/tags/v5.4.0_cm4.tar.gz changed yesterday from f711074a546bce04426c35e681446d69bc177435cd8f2f1395a52db64f52d100 to 32f226c31d7d1ff4a504404400603e047b99f405cd0c9a8f417f1f250251b829. Is this expected?

Possibly this is an issue on GitHub's side, so I mentioned it in https://github.com/orgs/community/discussions/46034#discussioncomment-10572206.

@ALABSTM

**Comment by tpudlik** [comment]
I figured it out. The repository has been renamed, from https://github.com/STMicroelectronics/cmsis_core/ to https://github.com/STMicroelectronics/cmsis-core/. The links all redirect (so both these URLs work), but the top-level folder in the compressed `.tar.gz` archive now has a different name (`cmsis-core`, not `cmsis_core`). So the checksum changed, too.

Is there a way to be notified of such changes in advance? It look us a while to figure this one out :(

**Comment by ALABSTM** [comment]
Hi @tpudlik,

Indeed, we identified a number of repositories to rename by replacing underscores by hyphens to enhance their visibility by search engines. This one is among the list.

As a way of notification, we can make an announcement [here](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions) to inform about this move and the list of impacted repositories.

Please excuse any inconvenience.

With regards,

**Comment by tpudlik** [comment]
Thank you, I subscribed to the announcements (i.e. Discussions on that repo)!

**Comment by ALABSTM** [comment]
Hi @tpudlik,

I hope you are fine. The list of the repositories to be renamed has been published [here](https://github.com/STMicroelectronics/STM32Cube_MCU_Overall_Offer/discussions/37). You should have been notified as you already subscribed to the announcements.

If you agree, we can close this issue so far.

With regards,

**Comment by ALABSTM** [comment]
Hi @tpudlik,

Please allow me to close this issue. Thank you again for the heads-up and apologies for any inconvenience caused.

With regards,

**Comment by tpudlik** [comment]
Thank you for the heads-up! I agree it makes sense to close the issue given there's a channel for announcing these changes.

**Comment by tpudlik** [comment]
Although, here's a thought: for future releases, could you attach the output of `git archive --output=[reponame].tar.gz` to the release? This will provide an archive with a stable SHA, even if the repos are renamed.
